title: Dom Silk
logo: "/assets/logo.JPG?raw=true"

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data professional with a global outlook and strong analytical background in Engineering. Interested in crypto, techno, and football  
  <br><br>
  Portfolio is a mix of academic and personal projects 
  <br><br>
  <a href="https://www.linkedin.com/in/dominicsilk/">View My LinkedIn Profile</a>  
theme: jekyll-theme-minimal
google_analytics: UA-167441035-1 # your Google Analytics tracking ID here
