title: Dom Silk
logo: "/assets/logo.JPG?raw=true"

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://www.linkedin.com/in/dominicsilk/">LinkedIn</a> |
  <a href="https://github.com/silkdom">GitHub</a>
  </p>
  <br>
  Chemical Engineer and Data Scientist with a global outlook. Also interested in football, crypto, techno, and analog photography

theme: jekyll-theme-minimal
google_analytics: UA-167441035-1 # your Google Analytics tracking ID here
