title: Dom Silk
logo: "/assets/logo.JPG?raw=true"

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Chemical Engineer and Data Scientist with a global outlook. Also interested in football, crypto, techno, and analog photography
  <br><br>
  Portfolio is a mix of academic and personal projects 
  <br><br>
  <a href="https://www.linkedin.com/in/dominicsilk/">View My LinkedIn Profile</a>  
theme: minima
google_analytics: UA-167441035-1 # your Google Analytics tracking ID here
